# Languages
#   Documentation: https://docs.hugoblox.com/reference/language/

fr:
  languageCode: fr-FR
  languageName: Français
  params:
    locale: fr-fr

en:
  languageCode: en-US
  languageName: English
  params:
    locale: en-us
