# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Pourquoi
    url: categories/pourquoi/
    weight: 20
  - name: Comment
    url: categories/comment/
    weight: 30
  - name: Combien
    url: categories/combien/
    weight: 40
  - name: À propos
    url: a-propos/
    weight: 50
  - name: Sujets
    url: tags/
    weight: 60
