############################
## HUGO MODULES
## Install or uninstall themes and plugins here.
## Docs: https://gohugo.io/hugo-modules/
############################

imports:
  - path: github.com/drgoulu/backlinks4hugo
  - path: github.com/HugoBlox/kit/modules/integrations/netlify
  - path: github.com/HugoBlox/kit/modules/blox
  - path: github.com/goulu/openbook4hugo
  - path: github.com/goulu/altmetric4hugo
  - path: github.com/drgoulu/headless-cms

# Install any Hugo Blox within the `hugo-blox/blox/` folder
mounts:
  - source: content
    target: content
  - source: content/posts
    target: assets/posts
    files:
      - "**/images/**"
      - "**/*.jpg"
      - "**/*.jpeg"
      - "**/*.png"
      - "**/*.gif"
      - "**/*.svg"
      - "**/*.webp"
  - source: content/quora
    target: assets/quora
    files:
      - "**/images/**"
      - "**/*.jpg"
      - "**/*.jpeg"
      - "**/*.png"
      - "**/*.gif"
      - "**/*.svg"
      - "**/*.webp"
  - source: layouts
    target: layouts
  - source: assets
    target: assets
  - source: static
    target: static
  - source: static/uploads
    target: assets/uploads
  - source: data
    target: data
  - source: hugo-blox/blox/community
    target: layouts/_partials/blox/community/
    files:
      - "**.html"
  - source: hugo-blox/blox/all-access
    target: layouts/_partials/blox/
    files:
      - "**.html"
  - source: hugo-blox/blox
    target: assets/dist/community/blox/
    files:
      - "**.css"
